-- Winter Festival 2026 — sesiones YouTube (breakbeat) enlazadas desde /mixes
INSERT INTO public.mixes (
  slug,
  title,
  artist_name,
  description_en,
  description_es,
  mix_type,
  year,
  duration_minutes,
  platform,
  video_url,
  embed_url,
  is_featured
) VALUES
  (
    'dj-tortu-winter-festival-2026',
    'Dj Tortu — Winter Festival 2026',
    'Dj Tortu',
    'Breakbeat DJ set from Winter Festival 2026 at Complejo Embrujo (14 March 2026).',
    'Sesión breakbeat del Winter Festival 2026 en Complejo Embrujo (14 de marzo de 2026).',
    'youtube_session',
    2026,
    NULL,
    'youtube',
    'https://youtu.be/sIik0dDr-Tg',
    'https://youtu.be/sIik0dDr-Tg',
    TRUE
  ),
  (
    'aggresivnes-winter-festival-2026',
    'Aggresivnes — Winter Festival 2026',
    'Aggresivnes',
    'Breakbeat set from Winter Festival 2026.',
    'Sesión breakbeat del Winter Festival 2026.',
    'youtube_session',
    2026,
    NULL,
    'youtube',
    'https://youtu.be/NRtY3-4uKjc',
    'https://youtu.be/NRtY3-4uKjc',
    TRUE
  ),
  (
    'destroyers-winter-festival-2026',
    'Destroyers — Winter Festival 2026',
    'Destroyers',
    'Breakbeat set from Winter Festival 2026.',
    'Sesión breakbeat del Winter Festival 2026.',
    'youtube_session',
    2026,
    NULL,
    'youtube',
    'https://youtu.be/5BDO8q9kV-E',
    'https://youtu.be/5BDO8q9kV-E',
    TRUE
  ),
  (
    'tilla-pink-winter-festival-2026',
    'Tilla Pink — Winter Festival 2026',
    'Tilla Pink',
    'Breakbeat set from Winter Festival 2026.',
    'Sesión breakbeat del Winter Festival 2026.',
    'youtube_session',
    2026,
    NULL,
    'youtube',
    'https://youtu.be/ex7I8Ou0zzY',
    'https://youtu.be/ex7I8Ou0zzY',
    TRUE
  ),
  (
    'paket-winter-festival-2026',
    'Paket — Winter Festival 2026',
    'Paket',
    'Breakbeat set from Winter Festival 2026.',
    'Sesión breakbeat del Winter Festival 2026.',
    'youtube_session',
    2026,
    NULL,
    'youtube',
    'https://youtu.be/nfeuPcLzaus',
    'https://youtu.be/nfeuPcLzaus',
    TRUE
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  artist_name = EXCLUDED.artist_name,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  mix_type = EXCLUDED.mix_type,
  year = EXCLUDED.year,
  duration_minutes = EXCLUDED.duration_minutes,
  platform = EXCLUDED.platform,
  video_url = EXCLUDED.video_url,
  embed_url = EXCLUDED.embed_url,
  is_featured = EXCLUDED.is_featured;
